### ISSUE TITLE
Remove collision

### ISSUE THREAD

**Issue by Michaelj15** [Achimobil/FS22_MapObjectsHider#2]
Hello,

It's for me not possible to remove the collisions from objects?
The object hider working fine, only the collision isn't.
Any suggestions?

**Comment by Achimobil** [comment]
Not everything can be removed. When the mapper has not done a good job and the visual is not in the collision or the collision is not on the top, then it could make strange things, I also have found some collisions which has to be removed multiple times to be removed because multiple collisions are over each other. 
Have you tried with an empty modfolder to remove the map object? Could be that another mod makes troubles.
Otherwise try to remove the not shown collision and make screens of how you remove it with all details of F1 and minimap and the download link to the map in modhub when not default map. I will then spend some time to see why this objects collision is not removable.

**Comment by Achimobil** [comment]
Because no response I close this as not reproducable
