### ISSUE TITLE
Hidden Objects Visible after Game restart

### ISSUE THREAD

**Issue by SunnyTeater** [Achimobil/FS22_MapObjectsHider#8]
Map: [Landersum ](https://www.farming-simulator.com/mod.php?lang=de&country=be&mod_id=264655)
Object Name: "decoration"
Multiplayer Dedicated Server: 1.12.0.0

After an object is hidden, it remains invisible only for the session. After reconnecting all objects are visible again. 
Other players must also hide the objects manually, a synchronization does not take place. 

Also, after hiding, a hitbox remains for the player Character, but for vehicles it is passable.

**Comment by Achimobil** [comment]
Please check behavior with the latest beta here in the releases and when it persists there also please tell exact where this object is you hide. A Screen with open minimap for example.
Does it also happen in simpgle player with that map

**Comment by SunnyTeater** [comment]
Just tested the [beta version](https://github.com/Achimobil/FS22_MapObjectsHider/releases/tag/1.0.1.0_beta_1), unfortunately still the same problem. 
It also makes no difference whether single player or multiplayer.
I have also tested other objects / fences and more, with all the same problem.

https://img.sunnyteater.de/ShareX_KR7wXuJ3Ye.jpg - map object example 
https://img.sunnyteater.de/FarmingSimulator2022Game_dp4KMuuopP.png - name of the object

**Comment by Achimobil** [comment]
Nice. starting LS with this map directly gives errors:
```
2023-08-25 13:28 Error: TransformGroup Kabel40m (node id 219311) has a zero scale
2023-08-25 13:28 Error: TransformGroup Kabel40m (node id 219742) has a zero scale
2023-08-25 13:28 Error: TransformGroup Kabel40m (node id 220191) has a zero scale
```

More Funny: I cuold not open the i3d in GE. So I could not check what is in there.
But I found out that because of the hirachie of the map the whole decoration is selected when targeting this element.
There are then over 1000 subobjects to remove which is to much for creating an md5 over the hirachie and so it is not reidentifiable. Based on that structure I change the code do get the ojbect to hide a little bit and This now works for me.

I could currently not test this in MP, but please use the new beta version to see if new hidden objects are still removed after restarting as I have that in SP currently. You find the version here: https://github.com/Achimobil/FS22_MapObjectsHider/releases/tag/1.0.1.1

**Comment by SunnyTeater** [comment]
tested the [1.0.1.1](https://github.com/Achimobil/FS22_MapObjectsHider/releases/tag/1.0.1.1)
in singleplayer it works fine.. but in multiplayer pressing H does nothing and also the menu cannot be opened. 
There are no errors in the game log from the server.
(yes i checked the key assignment)

**Comment by Achimobil** [comment]
Self checked on my server on Elmcreek. all three bindings works fine and I could hide and decolide objects.
The only found error I could reproduct is that when only decolide objects are there and you open the hidden objects menu then hide complete until restart of the game. 

I could not reproduce this on a default map, so when I should look deeper I need a way to reproduce on a default map without additional mods.
